# Generated by Django 3.1.3 on 2020-11-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20201128_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
