# Generated by Django 3.1.3 on 2020-11-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_auto_20201128_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='code',
            field=models.TextField(default='Write your code here', max_length=1000),
        ),
    ]
