# Generated by Django 3.1.3 on 2020-11-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_auto_20201128_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='instructions',
            field=models.TextField(max_length=1000),
        ),
    ]
