# Generated by Django 3.1.3 on 2020-11-28 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_auto_20201128_2333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hint',
        ),
    ]
